### ISSUE TITLE
Non-uniform capacity reporting

### ISSUE THREAD

**Issue by gattupally** [fractalio/integralstor_gridcell#123]
1) In Volumes, Space utilization is displayed in KB, Suggestion would be to display it in GB.
2) In Memory, Space utilization is displayed in KB, Suggestion would be to display it in MB.

**Comment by ramaseshan** [comment]
This should be fixed.

**Comment by naveen-fractlio** [comment]
We are able see the changes according to the requested sizes even in Memory utilization screen also with volume details. 
In memory Utilization screen we are able to see the string length of size display is standard too.

**Comment by naveen-fractlio** [comment]
This is fixed under tag #g1.1.1.rc1.

**Comment by naveen-fractlio** [comment]
After upgrade under tag g1.1.1.rc2 , the memory usage still shows in KB's in Total Memory column.

**Comment by gattupally** [comment]
Volume and Memory space utilization showing fine (GB, TB) in 
![memory size details](https://cloud.githubusercontent.com/assets/7625595/16115973/e759ee0e-33e7-11e6-9dde-01ed189a94b3.jpg)
![space utilization size details](https://cloud.githubusercontent.com/assets/7625595/16115972/e7563840-33e7-11e6-8144-13fecfa0fbb8.jpg)

GRIDCell   version g1.1.1.rc2
